using RecallSharp;

var scheduler = new FsrsScheduler();
var epoch = new DateTimeOffset(2026, 1, 1, 12, 0, 0, TimeSpan.Zero);

// The curve is defined so stability is exactly the point where recall reaches 90%.
var tenDayMemory = FsrsMemoryState.New(1, epoch) with
{
    Stage = MemoryStage.Review,
    Stability = 10,
    Difficulty = 5,
    LastReviewAt = epoch
};
AssertClose(
    scheduler.Retrievability(tenDayMemory, epoch.AddDays(10)),
    0.9,
    1e-12,
    "R(t = S) must equal 90%.");

// Check all four first-review outcomes and the minimal one-step policy.
var newCard = FsrsMemoryState.New(2, epoch);
var firstAgain = scheduler.Review(newCard, FsrsRating.Again, epoch);
var firstHard = scheduler.Review(newCard, FsrsRating.Hard, epoch);
var firstGood = scheduler.Review(newCard, FsrsRating.Good, epoch);
var firstEasy = scheduler.Review(newCard, FsrsRating.Easy, epoch);

AssertClose(firstAgain.Current.Stability!.Value, 0.212, 1e-12, "Initial Again stability.");
AssertClose(firstHard.Current.Stability!.Value, 1.2931, 1e-12, "Initial Hard stability.");
AssertClose(firstGood.Current.Stability!.Value, 2.3065, 1e-12, "Initial Good stability.");
AssertClose(firstEasy.Current.Stability!.Value, 8.2956, 1e-12, "Initial Easy stability.");
AssertEqual(firstAgain.Current.Stage, MemoryStage.Learning, "Again keeps a new card in Learning.");
AssertEqual(firstAgain.Interval, TimeSpan.FromMinutes(10), "Again restarts the learning step.");
AssertEqual(firstHard.Current.Stage, MemoryStage.Learning, "Hard is recalled but repeats the learning step.");
AssertEqual(firstHard.Interval, TimeSpan.FromMinutes(15), "Hard uses 1.5x a single learning step.");
AssertEqual(firstGood.Current.Stage, MemoryStage.Review, "Good graduates after the final learning step.");
AssertEqual(firstGood.Interval, TimeSpan.FromDays(2), "Initial Good interval.");
AssertEqual(firstEasy.Current.Stage, MemoryStage.Review, "Easy graduates immediately.");
AssertEqual(firstEasy.Interval, TimeSpan.FromDays(8), "Initial Easy interval.");

// Reference vector generated by the official FSRS-6 equations with the same parameters.
var secondGood = scheduler.Review(firstGood.Current, FsrsRating.Good, epoch.AddDays(2));
AssertClose(secondGood.PredictedRetrievability, 0.9094932559773545, 1e-12, "Retrievability reference vector.");
AssertClose(secondGood.Current.Stability!.Value, 10.964332335820698, 1e-10, "Recall stability reference vector.");
AssertEqual(secondGood.Interval, TimeSpan.FromDays(11), "Second Good interval.");

// Hard remains a passing grade, while Easy produces a larger gain than Good.
var hardRecall = scheduler.Review(firstGood.Current, FsrsRating.Hard, epoch.AddDays(2));
var easyRecall = scheduler.Review(firstGood.Current, FsrsRating.Easy, epoch.AddDays(2));
AssertEqual(hardRecall.Current.Stage, MemoryStage.Review, "Hard remains in Review.");
AssertEqual(hardRecall.Current.Lapses, 0, "Hard does not count as a lapse.");
AssertTrue(hardRecall.Current.Stability > firstGood.Current.Stability, "Hard increases stability after delayed recall.");
AssertTrue(easyRecall.Current.Stability > secondGood.Current.Stability, "Easy gains more stability than Good.");

// Forgetting a graduated card enters relearning and increments lapses once.
var lapse = scheduler.Review(secondGood.Current, FsrsRating.Again, epoch.AddDays(10));
AssertClose(lapse.Current.Stability!.Value, 1.4875035540165111, 1e-12, "Lapse stability reference vector.");
AssertEqual(lapse.Current.Stage, MemoryStage.Relearning, "Again from Review enters Relearning.");
AssertEqual(lapse.Current.Lapses, 1, "A review lapse increments the lapse count.");
AssertEqual(lapse.Interval, TimeSpan.FromMinutes(10), "A lapse uses the relearning step.");

// A successful same-day retry uses the FSRS-6 short-term equation and graduates.
var retry = scheduler.Review(lapse.Current, FsrsRating.Good, epoch.AddDays(10).AddMinutes(10));
AssertClose(retry.Current.Stability!.Value, 1.5226406803069095, 1e-12, "Same-day stability reference vector.");
AssertEqual(retry.Current.Stage, MemoryStage.Review, "A successful retry graduates after relearning.");
AssertTrue(retry.Current.Stability >= lapse.Current.Stability, "Same-day Good cannot reduce stability.");

// Interval limits and input validation are part of the public contract.
var cappedScheduler = new FsrsScheduler(FsrsOptions.Default with { MaximumIntervalDays = 30 });
AssertEqual(cappedScheduler.IntervalDays(1_000), 30, "Maximum interval is enforced.");
AssertThrows<ArgumentOutOfRangeException>(() => scheduler.IntervalDays(0), "Zero stability is rejected.");
AssertThrows<ArgumentOutOfRangeException>(
    () => scheduler.Review(secondGood.Current, FsrsRating.Good, epoch),
    "A review before the previous timestamp is rejected.");
AssertThrows<ArgumentException>(
    () => scheduler.Review(newCard with { Stability = 1, Difficulty = null }, FsrsRating.Good, epoch),
    "A partial memory state is rejected.");

// A scheduler takes a defensive copy of caller-provided parameter arrays.
var mutableParameters = FsrsOptions.DefaultParameters.ToArray();
var isolatedScheduler = new FsrsScheduler(FsrsOptions.Default with { Parameters = mutableParameters });
mutableParameters[0] = 999;
var isolatedAgain = isolatedScheduler.Review(FsrsMemoryState.New(3, epoch), FsrsRating.Again, epoch);
AssertClose(isolatedAgain.Current.Stability!.Value, 0.212, 1e-12, "Scheduler parameters are immutable after construction.");

Console.WriteLine("FSRS-6 conformance checks passed.");
return 0;

static void AssertClose(double actual, double expected, double tolerance, string message)
{
    if (Math.Abs(actual - expected) > tolerance)
        throw new InvalidOperationException($"{message} Expected {expected:R}; got {actual:R}.");
}

static void AssertEqual<T>(T actual, T expected, string message) where T : notnull
{
    if (!EqualityComparer<T>.Default.Equals(actual, expected))
        throw new InvalidOperationException($"{message} Expected {expected}; got {actual}.");
}

static void AssertTrue(bool value, string message)
{
    if (!value) throw new InvalidOperationException(message);
}

static void AssertThrows<TException>(Action action, string message) where TException : Exception
{
    try
    {
        action();
    }
    catch (TException)
    {
        return;
    }

    throw new InvalidOperationException(message);
}
